### ISSUE TITLE
Support for Inkscape 1.0

### ISSUE THREAD

**Issue by pbock** [evil-mad/axidraw#73]
As I was struggling to run Inkscape 0.92 on macOS (it kept crashing on launch), I tried Inkscape 1.0beta. It runs like a charm, but unfortunately the AxiDraw extensions don’t seem to be compatible. The only extension that is available is Hershey Text.

Here’s the content of my `extension-errors.log`:

```
Extension "Plot Optimization" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: extensions
  string: axidraw_svg_reorder.py

Extension "Plot Optimization" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: axidraw_svg_reorder.py

Extension "Disable XY Motors" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: extensions
  string: axidraw.py

Extension "Disable XY Motors" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: axidraw.py

Extension "AxiDraw Naming" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: extensions
  string: axidraw_naming.py

Extension "AxiDraw Naming" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: axidraw_naming.py

Extension "Hatch fill" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: extensions
  string: eggbot_hatch.py

Extension "Hatch fill" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: eggbot_hatch.py

Extension "AxiDraw Control" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: axidraw_control.py

Extension "EPS Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: ps2pdf

Extension "XFIG Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: fig2dev

Extension "GIMP XCF" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: gimp

Extension "Win32 Vector Print" failed to load because the extension is designed for Windows only.  This is caused by an improper .inx file for this extension.  An improper .inx file could have been caused by a faulty installation of Inkscape.
Extension "PostScript Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: ps2pdf
```

As Inkscape versions before 1.0 won’t be able to run on macOS 10.15 (Catalina) and above, it would be great if the AxiDraw extensions supported it.

If it’s any help, here’s the [documentation from the Inkscape Wiki on “Updating your Extension for 1.0”](https://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0)
